export enum scenarioName {
    GSMIdleMCI = 'GSMIdleMCI',
    WCDMAIdleMCI = 'WCDMAIdleMCI',
    LTEIdleMCI = 'LTEIdleMCI',
    ALLTechIdleMCI = 'ALLTechIdleMCI',
    GSMLongCallMCI = 'GSMLongCallMCI',
    WCDMALongCallMCI = 'WCDMALongCallMCI',
    GSMIdleMTN = 'GSMIdleMTN',
    WCDMAIdleMTN = 'WCDMAIdleMTN',
    LTEIdleMTN = 'LTEIdleMTN',
    ALLTechIdleMTN = 'ALLTechIdleMTN',
    GSMLongCallMTN = 'GSMLongCallMTN',
    WCDMALongCallMTN = 'WCDMALongCallMTN',
    FTP_DL_TH_MCI = 'FTP_DL_TH_MCI',
    FTP_DL_TH_MTN = 'FTP_DL_TH_MTN',
}